backend:
  name: git-gateway
  branch: master

media_library:
  name: cloudinary
  config:
    cloud_name: luvuong-le
    api_key: 298775176747774

publish_mode: editorial_workflow
site_url: https://lu-vuong-le.me/

collections:
  - name: "Blog"
    label: "Blog Post"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "select", multiple: true, options: ["design", "web", "ux", "ui", "programming"]}